[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit GFX Library @ 1.12.5
  zinggjm/GxEPD2 @ 1.6.7
  adafruit/Adafruit BME280 Library @ 2.3.0
  sensirion/Sensirion I2C SCD4x @ 1.1.0
  sensirion/Sensirion I2C SPS30 @ 1.0.0
  sensirion/Sensirion Core @ 0.7.3
